# nolint start: object_name_linter

#' @export
print.ohvbd.ids <- function(x, ...) {
  cat(paste0("Database: ", attr(x, "db"), "\n"))
  print(as.numeric(x))
}

#' @export
print.ohvbd.data.frame <- function(x, ...) {
  cat(paste0("Database: ", attr(x, "db"), "\n"))
  print(as.data.frame(x))
}

#' @export
print.ohvbd.ad.matrix <- function(x, ..., full=FALSE) {
  # If attr is null, default to <missing>
  metric <- attr(x, 'metric') %||% '<missing>'
  gid <- attr(x, 'gid') %||% '<missing>'
  cached <- attr(x, 'cached') %||% 'unknown'
  cli::cli_text("Areadata matrix for {.val {metric}} at gid level {.val {gid}}.")
  cli::cli_text("Cached: {.val {cached}}")
  cli::cli_text("Dates: {.val {head(colnames(m), 1)}}-{.val {tail(colnames(m), 1)}} ({.val {ncol(m)}})")
  cli::cli_text("Locations: {.val {nrow(m)}}")
  if (full) {
    cli::cli_h1("Data")
    NextMethod(object=matrix())
  }
}

#' @export
`[.ohvbd.ids` <- function(x, i) {
  new_ohvbd.ids(NextMethod(), db = attr(x, "db"))
}

#' @title Fetch specified data from a set of ids
#'
#' @description
#' This is a convenience method that infers and applies the correct fetch function for the input ids.
#' @author Francis Windram
#'
#' @param ids An object of type `ohvbd.ids` (generated from a search, manually packaged using `ohvbd.ids()` or generated by another function).
#' @param ... Any other arguments to be passed to the underlying fetch functions (see `fetch_vt()` and `fetch_vd()` for specific arguments).
#' @param rate maximum number of calls to the API per second.
#' @param connections number of simultaneous connections to the server at once. Maximum 8. **Do not enable unless you really need to** as this hits the server significantly harder than usual.
#' @param check_src toggle pre-checking of source data prior to get.
#' @param db An override for the db inferred by the data within `ids`. This is rarely necessary if you've used `ohvbd.ids()` to construct the id vector.
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#' @returns The extracted data, as an `ohvbd.responses` object.
#' @export
#' @examples
#' \dontrun{
#' find_vt_ids() %>% fetch()
#' }
fetch <- function(ids, ..., rate = 5, connections = 1, check_src = TRUE, db = NULL, basereq = NA) {
  UseMethod("fetch")
}

#' @export
fetch.ohvbd.ids <- function(ids, ..., rate = 5, connections = 1, check_src = TRUE, db = NULL, basereq = NA) {
  if (is.null(db)) {
    # If not overriding db, just use the one provided
    db <- attr(ids, "db")
  }
  finalfun <- switch(db,
                     "vt" = fetch_vt,
                     "vd" = fetch_vd,
                     cli::cli_abort("No method to fetch data from DB {.val {db}} for class{?es} {.cls {class(x)}}")
  )
  return(finalfun(ids, rate, connections, check_src, basereq))
}

#' @title Extract specified data from a set of responses
#'
#' @description
#' This is a convenience method that infers and applies the correct extractor for the input
#' @author Francis Windram
#'
#' @param res An object of type `ohvbd.responses` or `ohvbd.ad.matrix` generated from `fetch()`
#' and containing data from one of the supported databases.
#' @param ... Any arguments to be passed to the underlying extractors (see `extract_vt()` and `extract_ad()` for specific arguments).
#' @returns The extracted data, either as an `ohvbd.data.frame` or `ohvbd.ad.matrix` object.
#' @export
#' @examples
#' \dontrun{
#' find_vt_ids() %>% fetch() %>% extract(cols=c("Interactor1Species"))
#' fetch_ad(use_cache=TRUE) %>% extract(targetdate="2020-08-04")
#' }
extract <- function(res, ...) {
  UseMethod("extract")
}

#' @export
extract.ohvbd.responses <- function(res, ..., cols = NA, returnunique = FALSE, check_src = TRUE, db = NULL) {
  if (is.null(db)) {
    # If not overriding db, just use the one provided
    db <- attr(res, "db")
  }
  finalfun <- switch(db,
                     "vt" = extract_vt,
                     "vd" = extract_vd,
                     cli::cli_abort("No method to fetch data from DB {.val {db}} for class{?es} {.cls {class(x)}}")
  )
  return(finalfun(res, cols, returnunique, check_src))
}

#' @export
extract.ohvbd.ad.matrix <- function(res, ..., targetdate = NA, enddate = NA, places = NA, gid = NA, check_src = TRUE) {
  db <- attr(res, "db")
  return(extract_ad(res, targetdate, enddate, places, gid, check_src))
}
# nolint end
