#' @title Fetch VecTraits dataset/s by ID
#' @description Retrieve VecTraits dataset/s specified by their dataset ID.
#' @author Francis Windram
#'
#' @param ids a numeric ID or numeric vector of ids (preferably in an `ohvbd.ids` object) indicating the particular dataset/s to download.
#' @param rate maximum number of calls to the API per second.
#' @param connections number of simultaneous connections to the server at once. Maximum 8. **Do not enable unless you really need to** as this hits the server significantly harder than usual.
#' @param check_src toggle pre-checking of source data prior to get.
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#'
#' @return A list of [httr2 response][httr2::response()] objects, as an `ohvbd.responses` object.
#'
#' @examples
#' \dontrun{
#' fetch_vt(54)
#'
#' fetch_vt(c(54, 55, 56), rate=5)
#' }
#'
#' @concept vectraits
#'
#' @export
#'

fetch_vt <- function(ids, rate = 5, connections = 1, check_src = TRUE, basereq = NA) {

  max_conns <- 8

  if (is.null(attr(ids, "db")) && check_src) {
    cli_alert_warning("IDs not necessarily from VecTraits.")
  } else if (attr(ids, "db") != "vt" && check_src) {
    cli_abort(c("x" = "IDs not from VecTraits, Please use the {.fn fetch_{attr(ids, 'db')}} function.", "!" = "Detected db = {.val {attr(ids, 'db')}}"))
  }

  if (all(is.na(basereq))) {
    basereq <- vb_basereq()
  }

  if (length(ids) > 10) {
    # Preflight ssl check
    status <- tryCatch({
      preflight_test <- basereq %>% req_perform()  # nolint: object_usage_linter
      list("err_code" = 0, "err_obj" = NULL)
    }, error = function(e) {
      list("err_code" = 1, "err_obj" = e)
    })

    if (status$err_code == 1) {
      curl_err <- get_curl_err(status$err_obj)
      if (grepl("SSL certificate problem: unable to get local issuer certificate", curl_err)) {
        cat("\n")
        cli_alert_danger("Could not verify SSL certificate.")
        cli::cli_text("You may have success running {.fn set_ohvbd_compat} and then trying again.")
        cat("\n")
        cli_abort("SSL certificate problem: unable to get local issuer certificate")
      } else {
        cli_abort("Preflight found unknown error: {.val {curl_err}}")
      }
    }
  }

  # ids_to_find can be a single number or a vector and this works just fine!
  reqs <- ids %>% lapply(\(id) {
    basereq %>%
      req_url_path_append("vectraits-dataset") %>%
      req_url_path_append(id) %>%
      req_url_query("format" = "json") %>%
      req_error(body = vt_error_body) %>%
      req_headers(ohvbd = id) %>%  # Add additional header just so we can nicely handle failures
      req_throttle(rate)
  })
  if (connections <= 1) {
    resps <- reqs %>% req_perform_sequential(on_error = "continue", progress = list(
      name = "Vectraits Data",
      format = "Downloading {cli::pb_name} {cli::pb_current}/{cli::pb_total} {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}"
    ))
  } else {
    if (connections > max_conns) {
      cli_alert_warning("No more than {.val {max_conns}} simultaneous connection{?s} allowed!")
      cli_alert_info("Restricting to {.val {max_conns}} connection{?s}.")
      connections <- max_conns
    }
    resps <- reqs %>% req_perform_parallel(on_error = "continue", pool = curl::new_pool(total_con = 100, host_con = connections), progress = list(
      name = "Vectraits Data Parallel",
      format = "Downloading {cli::pb_name} {cli::pb_current}/{cli::pb_total} {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}"
    ))
  }

  fails <- resps %>% httr2::resps_failures()

  # Test if any failures were missing files (404s)
  missing <- find_vb_404s(fails)

  if (!is.null(missing)) {
    cli_alert_info("Incorrect ids:")
    cli::cli_ul(missing)
  }

  # Return the curl errors
  curl_err <- unique(unlist(lapply(fails, get_curl_err)))
  if (!is.null(curl_err)) {
    cli_alert_warning("curl errors: {.val {curl_err}}")
  }

  # Test to see if we got only errors
  if (length(fails) >= length(resps)) {
    # Only got errors!
    # Test to see if we got only a bunch of ssl errors
    if (any(grepl("SSL certificate problem: unable to get local issuer certificate", unlist(lapply(resps, get_curl_err, returnfiller = TRUE))))) {
      cat("\n")
      cli_alert_danger("Could not verify SSL certificate.")
      cli::cli_text("You may have success running {.fn set_ohvbd_compat} and then trying again.")
      cat("\n")
      cli_abort("SSL certificate problem: unable to get local issuer certificate")
    }
    cli_alert_warning("No records retrieved (are you sure the IDs are correct?).")
  }

  resps <- new_ohvbd.responses(l = resps, db = "vt")

  return(resps)
}
