#' @title Get current IDs in VecDyn
#' @description Get all the current dataset IDs in VecDyn, as a numeric vector.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#' @return A numeric vector of VecDyn dataset IDs.
#'
#' @examples
#' \dontrun{
#' find_vd_ids()
#' }
#'
#' @concept vecdyn
#'
#' @export
#'

find_vd_ids <- function(basereq = NA) {

  if (all(is.na(basereq))) {
    basereq <- vb_basereq()
  }

  resplist <- tryCatch({
    resp <- basereq %>%
      req_url_path_append("vecdynbyprovider") %>%
      req_url_query("format" = "json") %>%
      req_perform()
    list("resp" = resp, "err_code" = 0, "err_obj" = NULL)
  }, error = function(e) {
    # Get the last response instead
    list("resp" = last_response(), "err_code" = 1, "err_obj" = e)
  })

  if (resplist$err_code == 1) {
    if (grepl("SSL certificate problem: unable to get local issuer certificate", get_curl_err(resplist$err_obj, returnfiller = TRUE))) {
      cat("\n")
      cli_alert_danger("Could not verify SSL certificate.")
      cli::cli_text("You may have success running {.fn set_ohvbd_compat} and then trying again.")
      cat("\n")
      cli_abort("SSL certificate problem: unable to get local issuer certificate")
    }
    cli_abort("No records found.")
  }

  body <- resplist$resp %>% resp_body_json()
  outids <- as.numeric(body$ids)
  attr(outids, "db") <- "vd"
  return(outids)
}
