#' @title Get current IDs in VecDyn
#' @description Get all the current dataset IDs in VecDyn, as a numeric vector.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#' @return A numeric vector of VecDyn dataset IDs.
#'
#' @examples
#' \dontrun{
#' get_current_vd_ids()
#' }
#'
#' @export
#'

get_current_vd_ids <- function(basereq = NA) {

  if (all(is.na(basereq))) {
    basereq <- vb_basereq()
  }

  resplist <- tryCatch({
    resp <- basereq %>%
      req_url_path_append("vecdynbyprovider") %>%
      req_url_query("format" = "json") %>%
      req_perform()
    list("resp" = resp, "err_code" = 0)
  }, error = function(e) {
    # Get the last response instead
    list("resp" = last_response(), "err_code" = 1)
  })

  if (resplist$err_code == 1) {
    cli_abort("No records found.")
  }

  body <- resplist$resp %>% resp_body_json()
  return(as.numeric(body$ids))
}
