#' @title Get VecTraits dataset/s by ID
#' @description Retrieve VecTraits dataset/s specified by their dataset ID.
#' @author Francis Windram
#'
#' @param ids a numeric ID or numeric vector of ids indicating the particular dataset/s to download.
#' @param rate maximum number of calls to the API per second.
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#'
#' @return A list of [httr2 response][httr2::response()] objects.
#'
#' @examples
#' \dontrun{
#' get_vt_byid(54)
#'
#' get_vt_byid(c(54, 55, 56), rate=5)
#' }
#'
#' @concept vectraits
#'
#' @export
#'

get_vt_byid <- function(ids, rate = 5, basereq = NA) {

  if (is.null(attr(ids, "db"))) {
    cli_alert_warning("IDs not necessarily from VecTraits.")
  } else if (attr(ids, "db") != "vt") {
    cli_abort(c("x" = "IDs not from VecTraits, Please use the appropriate {.fn get_x} function.", "!" = "Detected db = {.val {attr(ids, 'db')}}"))
  }

  if (all(is.na(basereq))) {
    basereq <- vb_basereq()
  }

  # ids_to_find can be a single number or a vector and this works just fine!
  reqs <- ids %>% lapply(\(id) {
    basereq %>%
      req_url_path_append("vectraits-dataset") %>%
      req_url_path_append(id) %>%
      req_url_query("format" = "json") %>%
      req_error(body = vt_error_body) %>%
      req_headers(ohvbd = id) %>%  # Add additional header just so we can nicely handle failures
      req_throttle(rate)
  })
  resps <- reqs %>% req_perform_sequential(on_error = "continue", progress = list(
    name = "Vectraits Data",
    format = "Downloading {cli::pb_name} {cli::pb_current}/{cli::pb_total} {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}"
  ))

  attr(resps, "db") <- "vt"

  return(resps)
}
