#' @title Get VecTraits dataset/s by ID
#' @description Retrieve VecTraits dataset/s specified by their dataset ID.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()].
#' @param ids a numeric ID or numeric vector of ids indicating the particular dataset/s to download.
#' @param rate maximum number of calls to the API per second.
#'
#' @return A list of [httr2 response][httr2::response()] objects.
#'
#' @examples
#' \dontrun{
#' req <- vb_basereq()
#' get_vt_byid(req, 54)
#'
#' vb_basereq() %>% get_vt_byid(c(54, 55, 56), rate=5)
#' }
#'
#' @export
#'

get_vt_byid <-
function(basereq, ids, rate=5){
  # ids_to_find can be a single number or a vector and this works just fine!
  reqs <- ids %>% lapply(
    \(id) basereq %>%
      req_url_path_append("vectraits-dataset") %>%
      req_url_path_append(id) %>%
      req_url_query("format" = "json") %>%
      req_error(body=vt_error_body) %>%
      req_headers(ohvbd=id) %>%  # Add additional header just so we can nicely handle failures
      req_throttle(rate))
  resps <- reqs %>% req_perform_sequential(on_error = "continue", progress = list(
    name="Vectraits Data",
    format="Downloading {cli::pb_name} {cli::pb_current}/{cli::pb_total} {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}"))

  return(resps)
}
