#' @title Get current IDs in VecDyn
#' @description Get all the current dataset IDs in VecDyn, as a numeric vector.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()].
#' @return A numeric vector of VecDyn dataset IDs.
#'
#' @examples
#' \dontrun{
#' vb_basereq() %>%
#'   get_current_vd_ids()
#' }
#'
#' @export
#'

get_current_vd_ids <- function(basereq){
  resp <- tryCatch({
    resp <- basereq %>%
      req_url_path_append("vecdynbyprovider") %>%
      req_url_query("format" = "json") %>%
      req_perform()
    resp
  }, error = function(e){
    # Get the last response instead
    last_response()
  })

  if (resp$status_code == 404){
    stop(paste("No records found for", paste(keywords, collapse = " ")))
  }

  body <- resp %>% resp_body_json()
  return(as.numeric(body$ids))
}
