#' @title Get gadm mapping shapefiles
#' @description Retrieve AREAdata gadm mapping shapefiles specified by spatial scale (GID).
#' @author Francis Windram
#'
#' @param gid the spatial scale to retrieve (0 = country-level, 1=province-level...).
#' @param cache_location path to cache location (defaults to `./.adcache`).
#' @param refresh_cache force a refresh of the relevant cached data.
#' @param basereq the url of the AREAdata database (usually generated by [ad_basereq()]). If `NA`, uses the default.
#'
#' @return A SpatVector (from [terra::vect()]) of the requested shapefile.
#'
#' @examples
#' \dontrun{
#' get_gadm_sfs(gid=0)
#' }
#'
#' @concept areadata
#'
#' @export
#'

get_gadm_sfs <- function(gid = 0, cache_location = ".adcache", refresh_cache = FALSE, basereq = NA) {

  if (all(is.na(basereq))) {
    basereq <- ad_basereq()
  }

  cachefiles <- c("gadm-countries", "gadm-states", "gadm-counties")
  target_file <- cachefiles[gid + 1]
  # Try to load from adcache
  outshp <- NA

  if (!refresh_cache) {
    outshp <- tryCatch({
      cli_progress_message("{cli::symbol$pointer} Loading gadm cache...")
      vect(file.path(cache_location, paste0(target_file, ".shp")))
    }, error =  function(e) {
      cli_alert_warning("Loading failed.")
      NA
    })
  }

  if (any(!is.na(outshp))) {
    cli_alert_success("Loaded gadm cache.")
  } else {
    refresh_cache <- TRUE
  }

  if (refresh_cache) {
    cli_progress_message("{cli::symbol$pointer} Caching gadm data in {.path {cache_location}}...")
    final_url <- paste0(basereq, "data/gis/")
    # If not, try to retrieve from AD
    for (ext in c(".shp", ".shx", ".dbf", ".prj")) {
      cli_progress_message("{cli::symbol$pointer} Caching {.file {paste0(target_file, ext)}} in {.path {cache_location}}...")
      curl_download(paste0(final_url, target_file, ext), file.path(cache_location, paste0(target_file, ext)), quiet = TRUE)
      cli_alert_success("Cached {.file {paste0(target_file, ext)}} in {.path {cache_location}}.")
    }
    outshp <- tryCatch({
      cli_progress_message("{cli::symbol$pointer} Loading gadm cached data...")
      vect(file.path(cache_location, paste0(target_file, ".shp")))
    }, error = function(e) {
      cli_abort(c("x" = "Failed to load recently cached gadm data!"))
    })
    cli_alert_success("Loaded gadm cache.")
  }
  cli_progress_done()
  return(outshp)
}
