#' @title Get VecDyn dataset/s by ID
#' @description Retrieve VecDyn dataset/s specified by their dataset ID.
#' @author Francis Windram
#'
#' @param ids a numeric ID or numeric vector of ids indicating the particular dataset/s to download.
#' @param rate maximum number of calls to the API per second.
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()]. If `NA`, uses the default request.
#'
#' @return A list of [httr2 response][httr2::response()] objects.
#'
#' @examples
#' \dontrun{
#' get_vd_byid(54)
#'
#' get_vd_byid(c(423,424,425), rate=5)
#' }
#'
#' @export
#'

get_vd_byid <- function(ids, rate = 5, basereq = NA) {

  if (all(is.na(basereq))) {
    basereq <- vb_basereq()
  }

  # vd does not return nonexistent piids as 404,
  reqs <- ids %>% lapply(\(id) {
    basereq %>%
      req_url_path_append("vecdyncsv") %>%
      req_url_query("format" = "json", "piids" = id) %>%
      req_error(body = vd_error_body) %>%
      req_headers(ohvbd = id) %>%  # Add additional header just so we can nicely handle failures
      req_throttle(rate)
  })
  resps <- reqs %>% req_perform_sequential(on_error = "continue", progress = list(
    name = "VecDyn Data",
    format = "Downloading {cli::pb_name} {cli::pb_current}/{cli::pb_total} {cli::pb_bar} {cli::pb_percent} | ETA: {cli::pb_eta}"
  ))

  return(resps)
}
