#' @title Get AREAdata dataset
#' @description Retrieve AREAdata dataset/s specified by metric and spatial scale (GID).
#' @author Francis Windram
#'
#' @param basereq the url of the AREAdata database (usually generated by [ad_basereq()]).
#' @param metric the metric to retrieve from areadata.
#' @param gid the spatial scale to retrieve (0 = country-level, 1=province-level).
#'
#' @return A matrix of the requested data (with added attributes for gid and metric).
#'
#' @section Valid metrics:
#' The following metrics are valid (alternative names are listed in brackets):
#' - `temp` (*temperature*)
#' - `spechumid` (*specific humidity*)
#' - `relhumid` (*relative humidity*)
#' - `uv` (*ultraviolet*)
#' - `precip` (*precipitation, rainfall*)
#' - `popdens` (*population density, population*)
#' - `forecast` (*future climate, future*)
#'
#' @examples
#' \dontrun{
#' ad_basereq() %>% get_ad(metric="temp", gid=0)
#' }
#'
#' @export
#'

get_ad <-
function(basereq, metric="temp", gid=0){
  final_url <- paste0(basereq, "output/")
  poss_metrics <- c(
    "temp"=1, "temperature"=1,
    "spechumid"=2, "specific humidity"=2,
    "relhumid"=3, "relative humidity"=3,
    "uv"=4, "ultraviolet"=4,
    "precip"=5, "precipitation"=5, "rainfall"=5,
    "popdens"=6, "population density"=6, "population"=6,
    "forecast"=7, "future climate"=7, "future"=7
  )
  final_metrics <- c("temp", "spechumid", "relhumid", "uv", "precip", "popdens", "forecast")

  metric <- tolower(metric)
  if (metric %in% names(poss_metrics)){
    metricid <- poss_metrics[metric]
    final_metric <- final_metrics[metricid]
  } else {
    # Just for warning message
    warning(paste(
      "Metric",
      metric,
      'not an allowed metric!\n  Allowed metrics:\n  -',
      paste(final_metrics, collapse = ",\n  - "),
      '\nDefaulting to "temp"...'))
    final_metric <- "temp"
  }

  gid_str <- c("countries", "GID1")[gid + 1]

  if (metricid <= 5){
    # Daily Climate
    final_url <- paste0(final_url, final_metric, "-dailymean-", gid_str,"-cleaned.RDS")
  } else if (metricid == 6){
    # Population Density
    final_url <- paste0(final_url,"population-density-", gid_str,".RDS")
  } else {
    # Future climate Scenario Forecasts
    final_url <- paste0(final_url,"annual-mean-temperature-forecast-", gid_str,".RDS")
  }

  # Add gid attribute to matrix to allow easier parsing later down the line
  outmat <- readRDS(url(final_url))
  attr(outmat, "gid") <- gid
  attr(outmat, "adtype") <- final_metric

  return(outmat)
}
