#' @title Get current IDs in VecTraits
#' @description Get all the current dataset IDs in VecTraits, as a numeric vector.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()].
#' @return A numeric vector of VecTraits dataset IDs.
#'
#' @examples
#' \dontrun{
#' req <- vb_basereq()
#' get_current_vt_ids(req)
#' }
#'
#' @export
#'

get_current_vt_ids <-
function(basereq){
  resplist <- tryCatch({
    resp <- basereq %>%
      req_url_path_append("vectraits-explorer") %>%
      req_url_query("format" = "json") %>%
      req_perform()
    list("resp"=resp, "err_code"=0)
  }, error = function(e){
    # Get the last response instead
    list("resp"=last_response(), "err_code"=1)
  })

  if (resplist$err_code == 1){
    cli_abort("No records found.")
  }

  body <- resplist$resp %>% resp_body_json()
  return(as.numeric(body$ids))
}
