#' @title Get AREAdata dataset
#' @description Retrieve AREAdata dataset/s specified by metric and spatial scale (GID).
#' @author Francis Windram
#'
#' @param metric the metric to retrieve from areadata.
#' @param gid the spatial scale to retrieve (0 = country-level, 1=province-level ...).
#' @param use_cache load files from cache if possible, and save them if not present.
#' @param cache_location path to cache location (defaults to user directory obtained from [tools::R_user_dir()][tools::R_user_dir()]).
#' @param refresh_cache force a refresh of the relevant cached data.
#' @param basereq the url of the AREAdata database (usually generated by [ad_basereq()]). If `NA`, uses the default.
#'
#' @return A matrix of the requested data (with added attributes for gid and metric).
#'
#' @section Valid metrics:
#' The following metrics are valid (alternative names are listed in brackets):
#' - `temp` (*temperature*)
#' - `spechumid` (*specific humidity*)
#' - `relhumid` (*relative humidity*)
#' - `uv` (*ultraviolet*)
#' - `precip` (*precipitation, rainfall*)
#' - `popdens` (*population density, population*)
#' - `forecast` (*future climate, future*)
#'
#' @examples
#' \dontrun{
#' get_ad(metric="temp", gid=0)
#' }
#'
#' @concept areadata
#'
#' @export
#'

get_ad <- function(metric = "temp", gid = 0, use_cache = FALSE, cache_location = "user", refresh_cache = FALSE, basereq = NA) {

  if (all(is.na(basereq))) {
    basereq <- ad_basereq()
  }

  if (gid > 1 && !use_cache) {
    cli_alert_warning("GID2 datasets are quite large.")
    cli_alert_info("It is recommended to set {.arg use_cache=TRUE} to enable caching.")
  }

  if (tolower(cache_location) == "user") {
    # Have to do some horrible path substitution to make this work nicely on windows. It may cause errors later in which case another solution may be better.
    cache_location <- file.path(gsub("\\\\", "/", tools::R_user_dir("ohvbd", which = "cache")), "adcache")
  }

  loaded_cache <- FALSE
  final_url <- paste0(basereq, "output/")
  # TODO: Consider using match.arg() to do fuzzy matching because that'd be super cool
  poss_metrics <- c(
    "temp" = 1, "temperature" = 1,
    "spechumid" = 2, "specific humidity" = 2,
    "relhumid" = 3, "relative humidity" = 3,
    "uv" = 4, "ultraviolet" = 4,
    "precip" = 5, "precipitation" = 5, "rainfall" = 5,
    "popdens" = 6, "population density" = 6, "population" = 6,
    "forecast" = 7, "future climate" = 7, "future" = 7
  )
  final_metrics <- c("temp", "spechumid", "relhumid", "uv", "precip", "popdens", "forecast")

  metric <- tolower(metric)
  if (metric %in% names(poss_metrics)) {
    metricid <- poss_metrics[metric]
    final_metric <- final_metrics[metricid]
  } else {
    # Just for warning message
    cli_alert_warning("Metric {.val {metric}} not an allowed metric!")
    cli_rule(left = "Allowed metrics")
    cli_ul(final_metrics)
    cli_rule()
    final_metric <- "temp"
    metricid <- 1
    cli_alert_warning("Defaulting to {.val {final_metric}}")
  }
  outmat <- NA
  # Try to load cache
  if (use_cache && !refresh_cache) {
    outmat <- tryCatch({
      cli_progress_message("{cli::symbol$pointer} Loading AREAdata cache: {final_metric}-{gid} ...")
      suppressWarnings(read_ad_cache(cache_location, final_metric, gid))
    }, error = function(e) {
      cli_alert_danger("Failed to load AREAdata cache: {final_metric}-{gid}!")
      NA
    })
  }

  if (any(!is.na(outmat))) {
    loaded_cache <- TRUE
    cli_alert_success("Loaded AREAdata cache {final_metric}-{gid}.")
  }

  if (!loaded_cache) {
    cli_progress_message("{cli::symbol$pointer} Loading AREAdata {final_metric}-{gid} from github...")
    gid_str <- c("countries", "GID1", "GID2")[gid + 1]

    if (gid < 2) {
      if (metricid <= 5) {
        # Daily Climate
        final_url <- paste0(final_url, final_metric, "-dailymean-", gid_str, "-cleaned.RDS")
      } else if (metricid == 6) {
        # Population Density
        final_url <- paste0(final_url, "population-density-", gid_str, ".RDS")
      } else {
        # Future climate Scenario Forecasts
        final_url <- paste0(final_url, "annual-mean-temperature-forecast-", gid_str, ".RDS")
      }
    } else {
      if (metricid <= 5) {
        # These links may change upon new uploads?
        final_url <- switch(final_metric,
                            "temp" = "https://figshare.com/ndownloader/files/35067691",
                            "spechumid" = "https://figshare.com/ndownloader/files/35068528",
                            "relhumid" = "https://figshare.com/ndownloader/files/35070109",
                            "precip" = "https://figshare.com/ndownloader/files/35074111",
                            "uv" = "https://figshare.com/ndownloader/files/35071861")
      } else if (metricid == 6) {
        cli_alert_warning("{.val {final_metric}} not available at GID level 2. Defaulting to GID level 1...")
        final_url <- paste0(final_url, "population-density-GID1.RDS")
      } else {
        cli_alert_warning("{.val {final_metric}} not available at GID level 2. Defaulting to GID level 1...")
        final_url <- paste0(final_url, "annual-mean-temperature-forecast-GID1.RDS")
      }
    }

    # Add gid attribute to matrix to allow easier parsing later down the line
    outmat <- readRDS(url(final_url))
    cli_alert_success("Loaded AREAdata {final_metric}-{gid} from github.")

    attr(outmat, "gid") <- gid
    attr(outmat, "metric") <- final_metric
    attr(outmat, "db") <- "ad"
    attr(outmat, "cached") <- FALSE
  }

  if (use_cache) {
    if (!loaded_cache || refresh_cache) {
      cli_progress_message("{cli::symbol$pointer} Caching AREAdata {final_metric}-{gid} in {.path {cache_location}}...")
      write_ad_cache(outmat, path = cache_location, metric = final_metric, gid = gid, format = "rda")
      cli_alert_success("Cached AREAdata {final_metric}-{gid} in {.path {cache_location}}.")
    }
  }

  cli_progress_done()

  return(outmat)
}
