#' @title Get current IDs in VecTraits
#' @description Get all the current dataset IDs in VecTraits, as a numeric vector.
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [generate_vb_basereq()].
#' @return A numeric vector of VecTraits dataset IDs.
#'
#' @examples
#' \dontrun{
#' req <- generate_vb_basereq()
#' get_current_vt_ids(req)
#' }
#'
#' @export
#'

get_current_vt_ids <-
function(basereq){
  resp <- basereq %>%
  req_url_path_append("vectraits-explorer") %>%
  req_url_query("format" = "json") %>%
  req_perform()
  overalldata <- resp %>% resp_body_json()
  present_ids <- as.numeric(overalldata$ids)
  return(present_ids)
}
