#' @title Search VecTraits by keyword
#' @description Retrieve the IDs for any VecTraits datasets matching the given keywords
#'
#' @author Francis Windram
#'
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [vb_basereq()].
#' @param keywords either a string of search terms separated by spaces, or a vector of keywords.
#'
#' @return A numeric vector of VecTraits dataset IDs.
#'
#' @examples
#' \dontrun{
#' vb_basereq() %>%
#'   search_vt("Aedes aegypti")
#'
#' vb_basereq() %>%
#'   search_vt(c("Aedes", "aegypti"))
#'
#' }
#'
#' @export
#'

search_vt <-
function(basereq, keywords){
  resp <- tryCatch({
    resp <- basereq %>%
      req_url_path_append("vectraits-explorer") %>%
      req_url_query("format" = "json") %>%
      req_url_query("keywords" = keywords, .multi = space_collapse) %>%
      req_perform()
    resp
  }, error = function(e){
    # Get the last response instead
    last_response()
  })

  if (resp$status_code == 404){
    cli_abort("No records found for {.val {keywords}}")
  }

  body <- resp %>% resp_body_json()
  return(as.numeric(body$ids))
}
